### ISSUE TITLE
Error caught during inference

### ISSUE THREAD

**Issue by d-li14** [taoyang1122/MutualNet#3]
Hi, I ran the inference with pretrained mobilenetv2 but encountered the following error. Any idea about how to solve it?
```shell
07/15 07:10:27 PM | Start testing.
07/15 07:13:35 PM | VAL 188.3s 1.0x-224 Epoch:0/250 Loss:1.0739 Acc:0.730
07/15 07:16:41 PM | VAL 373.9s 0.9x-224 Epoch:0/250 Loss:1.2317 Acc:0.699
07/15 07:20:01 PM | VAL 574.2s 0.7x-224 Epoch:0/250 Loss:2.9944 Acc:0.377
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    main()
  File "train.py", line 237, in main
    train_val_test()
  File "train.py", line 213, in train_val_test
    test(last_epoch, val_loader, model_wrapper, criterion, train_loader)
  File "train.py", line 144, in test
    model = ComputePostBN.ComputeBN(model, postloader, resolution)
  File "/home/rll/MutualNet/ComputePostBN.py", line 47, in ComputeBN
    _ = net(F.interpolate(img, (resolution, resolution), mode='bilinear', align_corners=True))
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rll/MutualNet/models/mobilenet_v2.py", line 120, in forward
    x = self.features(x)
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rll/anaconda3/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 554, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
RuntimeError: Given input size: (1280x6x6). Calculated output size: (1280x0x0). Output size is too small

```

**Comment by taoyang1122** [comment]
@d-li14 Hi, this seems to be caused by the nn.AvgPool2d in different Pytorch version. You can modify the nn.AvgPool2d to nn.AdaptiveAvgPool2d((1, 1)) in the model definition file. This should work.

**Comment by d-li14** [comment]
@taoyang1122 Yeah, that's it. I just figured out the issue. Sorry for my brainless question.

**Comment by d-li14** [comment]
@taoyang1122 Hi, I started to perform inference but got inferior results compared to the paper. The log below shows my test results. Then what could be wrong?
```shell
07/15 02:11:15 PM | Start testing.
07/15 02:20:45 PM | VAL 569.3s 1.0x-224 Epoch:0/250 Loss:1.0734 Acc:0.730
07/15 02:22:23 PM | VAL 667.5s 0.95x-224 Epoch:0/250 Loss:1.1640 Acc:0.710
07/15 02:23:58 PM | VAL 762.5s 0.9x-224 Epoch:0/250 Loss:1.2319 Acc:0.698
07/15 02:25:33 PM | VAL 857.6s 0.85x-224 Epoch:0/250 Loss:1.2630 Acc:0.691
07/15 02:27:11 PM | VAL 955.5s 0.8x-224 Epoch:0/250 Loss:1.3330 Acc:0.677
07/15 02:28:49 PM | VAL 1053.2s 0.75x-224 Epoch:0/250 Loss:1.4780 Acc:0.647
07/15 02:30:22 PM | VAL 1146.6s 0.7x-224 Epoch:0/250 Loss:3.0046 Acc:0.377
07/15 02:31:58 PM | VAL 1242.6s 0.65x-224 Epoch:0/250 Loss:5.2977 Acc:0.104
07/15 02:33:35 PM | VAL 1339.4s 0.6x-224 Epoch:0/250 Loss:6.9780 Acc:0.016
07/15 02:35:10 PM | VAL 1434.9s 0.55x-224 Epoch:0/250 Loss:7.6256 Acc:0.006
07/15 02:36:46 PM | VAL 1531.0s 0.5x-224 Epoch:0/250 Loss:7.9591 Acc:0.003
07/15 02:38:23 PM | VAL 1627.1s 0.45x-224 Epoch:0/250 Loss:8.2704 Acc:0.002
07/15 02:39:59 PM | VAL 1723.1s 0.4x-224 Epoch:0/250 Loss:8.2260 Acc:0.001
07/15 02:41:35 PM | VAL 1819.4s 0.35x-224 Epoch:0/250 Loss:8.4459 Acc:0.001
07/15 02:43:07 PM | VAL 1911.3s 0.3x-224 Epoch:0/250 Loss:8.1888 Acc:0.001
07/15 02:44:43 PM | VAL 2007.7s 0.25x-224 Epoch:0/250 Loss:8.2573 Acc:0.001
07/15 02:46:20 PM | VAL 2104.5s 1.0x-192 Epoch:0/250 Loss:1.1236 Acc:0.719
07/15 02:47:57 PM | VAL 2201.2s 0.95x-192 Epoch:0/250 Loss:1.2144 Acc:0.700
07/15 02:49:33 PM | VAL 2297.5s 0.9x-192 Epoch:0/250 Loss:1.2865 Acc:0.685
07/15 02:51:05 PM | VAL 2389.5s 0.85x-192 Epoch:0/250 Loss:1.3167 Acc:0.678
07/15 02:52:41 PM | VAL 2485.5s 0.8x-192 Epoch:0/250 Loss:1.3974 Acc:0.662
07/15 02:54:16 PM | VAL 2580.2s 0.75x-192 Epoch:0/250 Loss:1.5429 Acc:0.630
07/15 02:55:52 PM | VAL 2676.5s 0.7x-192 Epoch:0/250 Loss:3.0701 Acc:0.363
07/15 02:57:28 PM | VAL 2772.7s 0.65x-192 Epoch:0/250 Loss:5.3773 Acc:0.103
07/15 02:59:03 PM | VAL 2867.3s 0.6x-192 Epoch:0/250 Loss:7.1297 Acc:0.017
07/15 03:00:37 PM | VAL 2961.8s 0.55x-192 Epoch:0/250 Loss:7.8223 Acc:0.006
07/15 03:02:12 PM | VAL 3056.9s 0.5x-192 Epoch:0/250 Loss:8.1423 Acc:0.003
07/15 03:03:47 PM | VAL 3151.4s 0.45x-192 Epoch:0/250 Loss:8.4738 Acc:0.001
07/15 03:05:22 PM | VAL 3246.8s 0.4x-192 Epoch:0/250 Loss:8.4143 Acc:0.001
07/15 03:06:56 PM | VAL 3340.5s 0.35x-192 Epoch:0/250 Loss:8.6457 Acc:0.001
07/15 03:08:32 PM | VAL 3436.3s 0.3x-192 Epoch:0/250 Loss:8.3746 Acc:0.001
07/15 03:10:06 PM | VAL 3530.7s 0.25x-192 Epoch:0/250 Loss:8.3891 Acc:0.001
07/15 03:11:43 PM | VAL 3627.4s 1.0x-160 Epoch:0/250 Loss:1.2113 Acc:0.700                                                                  
07/15 03:13:19 PM | VAL 3723.5s 0.95x-160 Epoch:0/250 Loss:1.3074 Acc:0.679                                                                 
07/15 03:14:56 PM | VAL 3820.3s 0.9x-160 Epoch:0/250 Loss:1.3816 Acc:0.663
07/15 03:16:30 PM | VAL 3914.2s 0.85x-160 Epoch:0/250 Loss:1.4116 Acc:0.658
07/15 03:18:08 PM | VAL 4012.2s 0.8x-160 Epoch:0/250 Loss:1.5004 Acc:0.640
07/15 03:19:43 PM | VAL 4107.2s 0.75x-160 Epoch:0/250 Loss:1.6646 Acc:0.605
07/15 03:21:15 PM | VAL 4199.4s 0.7x-160 Epoch:0/250 Loss:3.2619 Acc:0.334
07/15 03:22:51 PM | VAL 4295.1s 0.65x-160 Epoch:0/250 Loss:5.4940 Acc:0.089
07/15 03:24:26 PM | VAL 4390.2s 0.6x-160 Epoch:0/250 Loss:7.2989 Acc:0.016 
07/15 03:25:56 PM | VAL 4480.9s 0.55x-160 Epoch:0/250 Loss:7.9815 Acc:0.006
07/15 03:27:35 PM | VAL 4579.1s 0.5x-160 Epoch:0/250 Loss:8.3407 Acc:0.003 
07/15 03:29:13 PM | VAL 4677.1s 0.45x-160 Epoch:0/250 Loss:8.7437 Acc:0.001
07/15 03:30:48 PM | VAL 4772.5s 0.4x-160 Epoch:0/250 Loss:8.7003 Acc:0.001 
07/15 03:32:24 PM | VAL 4868.2s 0.35x-160 Epoch:0/250 Loss:8.9356 Acc:0.001
07/15 03:33:59 PM | VAL 4963.8s 0.3x-160 Epoch:0/250 Loss:8.6661 Acc:0.001 
07/15 03:35:33 PM | VAL 5058.0s 0.25x-160 Epoch:0/250 Loss:8.6099 Acc:0.001
07/15 03:37:09 PM | VAL 5153.6s 1.0x-128 Epoch:0/250 Loss:1.3822 Acc:0.664 
07/15 03:38:50 PM | VAL 5254.9s 0.95x-128 Epoch:0/250 Loss:1.4947 Acc:0.641
07/15 03:40:32 PM | VAL 5356.4s 0.9x-128 Epoch:0/250 Loss:1.5842 Acc:0.621 
07/15 03:42:16 PM | VAL 5460.8s 0.85x-128 Epoch:0/250 Loss:1.6207 Acc:0.614
07/15 03:43:53 PM | VAL 5557.8s 0.8x-128 Epoch:0/250 Loss:1.7297 Acc:0.593                                                                                                                                                                 
07/15 03:45:29 PM | VAL 5653.8s 0.75x-128 Epoch:0/250 Loss:1.9221 Acc:0.555
07/15 03:47:04 PM | VAL 5748.9s 0.7x-128 Epoch:0/250 Loss:3.6602 Acc:0.275 
07/15 03:48:39 PM | VAL 5843.5s 0.65x-128 Epoch:0/250 Loss:5.8250 Acc:0.073
07/15 03:50:18 PM | VAL 5942.1s 0.6x-128 Epoch:0/250 Loss:7.6267 Acc:0.013 
07/15 03:51:57 PM | VAL 6042.1s 0.55x-128 Epoch:0/250 Loss:8.3304 Acc:0.005
07/15 03:53:38 PM | VAL 6142.6s 0.5x-128 Epoch:0/250 Loss:8.7892 Acc:0.003 
07/15 03:55:17 PM | VAL 6241.7s 0.45x-128 Epoch:0/250 Loss:9.1729 Acc:0.001
07/15 03:56:56 PM | VAL 6340.6s 0.4x-128 Epoch:0/250 Loss:9.2113 Acc:0.001 
07/15 03:58:36 PM | VAL 6441.0s 0.35x-128 Epoch:0/250 Loss:9.4091 Acc:0.001
07/15 04:00:15 PM | VAL 6539.2s 0.3x-128 Epoch:0/250 Loss:9.1579 Acc:0.001 
07/15 04:01:55 PM | VAL 6639.4s 0.25x-128 Epoch:0/250 Loss:8.9824 Acc:0.001
```
These are the modifications I made to the config file.
```diff
@@ -1,8 +1,8 @@
 # data
 dataset: imagenet1k
 data_transforms: imagenet1k_mobile
-dataset_dir: /home/ubuntu/yang/data/ImageNet/ILSVRC/Data/CLS-LOC
-data_loader_workers: 4
+dataset_dir: /home/lid/data/ILSVRC2012/
+data_loader_workers: 32
 
 # info
 num_classes: 1000
@@ -31,10 +31,10 @@ batch_size: 1024
 log_dir: logs/
 model: models.mobilenet_v2
 reset_parameters: True
-width_mult_list: [0.7, 0.9, 1.0]
+width_mult_list: [0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0]
 width_mult_range: [0.7, 1.0]
 resolution_list: [224, 192, 160, 128]
 # test pretrained resume
-test_only: False
-pretrained: ''
+test_only: True
+pretrained: './mnet2.pt'
 resume: ''
```

**Comment by taoyang1122** [comment]
@d-li14 Hi, the reason is that the [divisor](https://github.com/taoyang1122/MutualNet/blob/master/models/slimmable_ops.py#L5) in the released codes is 1 while the model I released is trained with divisor=8. Revising it to 8 should be ok. Thanks for pointing it out, I will update it.
Another thing is that MobileNet v2 is trained with width range [0,7, 1.0] as explained in the paper, so it is meaningless to go below 0.7. If you want a larger adaptive range, you need to re-trained it with a larger width range or smaller resolution.

**Comment by d-li14** [comment]
Thank you, it actually should be divisible by 8 following the original mobilenet model series.
I also expect it will not work under the lower boundary of training width, but 0.25x-1.0x is the range mentioned in the "Model Inference" section of the paper. I want to see what will happen by adding the widths below 0.7, merely out of curiosity. So I think it would be better if you could clearly claim in the "Model Inference" section 0.25x-1.0x for MobileNetV1 while 0.7x-1.0x for MobileNetV2.

**Comment by taoyang1122** [comment]
Yes, I will make it clear. Thanks.
