### ISSUE TITLE
AttributeError: Can't pickle local object 'get_cifar.<locals>.<lambda>'

### ISSUE THREAD

**Issue by kangpeilun** [taoyang1122/MutualNet#5]
I use the windows to train model, but I get this problem.

--------------------------------------------------------------------------

  File "D:\桌面\火灾大创\相关模型代码\MutualNet-目标检测等\MutualNet-master\ComputePostBN.py", line 44, in ComputeBN
    for batch_idx, (inputs, targets) in enumerate(postloader):
  File "E:\Anaconda3\envs\mutual\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "E:\Anaconda3\envs\mutual\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "E:\Anaconda3\envs\mutual\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "E:\Anaconda3\envs\mutual\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Anaconda3\envs\mutual\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\Anaconda3\envs\mutual\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\Anaconda3\envs\mutual\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_cifar.<locals>.<lambda>'

(E:\Anaconda3\envs\mutual) D:\桌面\火灾大创\相关模型代码\MutualNet-目标检测等\MutualNet-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda3\envs\mutual\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "E:\Anaconda3\envs\mutual\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] 拒绝访问。

--------------------------------------------------------------------------

I have searched the internet，they say：

Pytorch的DataLoader模块，当 num_workers设置为非0时，在linux下运行正常，但是在Windows下出现AttributeError: Can’t pickle local object ‘Sharpen..create_matrices’，出现该异常的原因是pickle模块不能序列化lambda function。
在Unix/Linux下，multiprocessing模块封装了fork（）调用，是我们不需要关注fork（）的细节。由于windows没有fork调用，因此，multiprocessing需要“模拟”出fork的效果，父进程所有Python对象都必须通过pickle序列号再传到子进程中去。所以，如果multiprocessing在Windows下调用失败了，要先考虑是不是pickle失败了。

--------------------------------------------------------------------------

I think the reason is multiprocessing , so I want to shut it down， and I change ‘data_loader_workers==1’，but it still not work
code below：
# data
#dataset: imagenet1k
#data_transforms: imagenet1k_mobile
##dataset_dir: /home/ubuntu/yang/data/ImageNet/ILSVRC/Data/CLS-LOC
#dataset_dir: /home/ubuntu/yang/data/ImageNet/ILSVRC/Data/CLS-LOC
#data_loader_workers: 1
dataset: cifar100

# test pretrained resume
test_only: True
pretrained: '../models/mobilenetv1.pt'
resume: ''

As you can see，My computer dont have enough memory，so I want to use cifar100，but still not work。
I have never used pytorch before，I feel sorry

**Comment by taoyang1122** [comment]
@kangpeilun Hi, I didn't try to run on Windows so I can not really figure out what is the issue. But as you said, if it is with the multiprocessing, you may try to set the data_loader_workers=0. But this may make the dataloader slow.

**Comment by kangpeilun** [comment]
Thanks，I have solved that problem by noting one line of your code，but I think this not a good way。And I will try your advice。
